// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using team_hub_auth.Data;

#nullable disable

namespace team_hub_auth.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260730120516_AddUserNameSurnameIndexes")]
    partial class AddUserNameSurnameIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("team_hub_auth.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("team_hub_auth.Models.User", b =>
                {
                    b.OwnsOne("team_hub_auth.Models.UserCredentials", "Credentials", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PasswordHash")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Password");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("team_hub_auth.Models.UserIdentity", "Identity", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Email");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Username");

                            b1.HasKey("UserId");

                            b1.HasIndex("Email")
                                .IsUnique()
                                .HasFilter("\"Email\" <> ''");

                            b1.HasIndex("Username")
                                .IsUnique();

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("team_hub_auth.Models.UserProfile", "Profile", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Name");

                            b1.Property<string>("Surname")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Surname");

                            b1.HasKey("UserId");

                            b1.HasIndex("Name");

                            b1.HasIndex("Surname");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("team_hub_auth.Models.UserSecurity", "Security", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<int>("FailedLoginAttempts")
                                .HasColumnType("integer")
                                .HasColumnName("FailedLoginAttempts");

                            b1.Property<DateTimeOffset?>("LockoutUntil")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LockoutUntil");

                            b1.Property<DateTimeOffset?>("RefreshTokenExpiresAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("RefreshTokenExpiresAt");

                            b1.Property<string>("RefreshTokenHash")
                                .HasColumnType("text")
                                .HasColumnName("RefreshTokenHash");

                            b1.HasKey("UserId");

                            b1.HasIndex("RefreshTokenHash")
                                .IsUnique();

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Credentials")
                        .IsRequired();

                    b.Navigation("Identity")
                        .IsRequired();

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("Security")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
